run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - golang.zabbix.com/sdk
  gci:
    sections:
      - standard
      - default
      - prefix(golang.zabbix.com)
  gofmt:
    simplify: true
  goimports:
    local-prefixes: golang.zabbix.com
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
  goconst:
    min-occurrences: 4

linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - errcheck
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - funlen
    - gochecknoglobals
    - godox
    - wsl

issues:
  exclude-rules:
    # Disable certain linters for generated code
    - path: ".*_test\\.go"
      linters:
        - gocognit
        - goconst
        - gocyclo
    
    # Allow globals in main.go for plugin variables
    - path: "main\\.go"
      linters:
        - gochecknoglobals

  max-issues-per-linter: 0
  max-same-issues: 0 